const state = { allergens: [], menu: [], selected: new Set(), mode: 'safe', q: '' };
function pill(a){ return `<label class="chip"><input type="checkbox" value="${a.code}"><span class="code">${a.code}</span><span class="name">· ${a.name}</span></label>`; }
function codeBadge(code){ return `<span class="badge">${code}</span>`; }
function renderFilters(){ const el = document.getElementById('activeFilters'); if (!el) return; el.innerHTML = state.selected.size ? ('Selected: ' + Array.from(state.selected).map(codeBadge).join(' ')) : ''; }
function matchesQ(d){ if(!state.q) return true; const q=state.q.toLowerCase(); return d.dish.toLowerCase().includes(q) || (d.notes||'').toLowerCase().includes(q); }
function isSafe(d){ for(const c of state.selected){ if(d.codes.includes(c)) return false; } return true; }
function containsSel(d){ if(!state.selected.size) return false; for(const c of state.selected){ if(d.codes.includes(c)) return true; } return false; }
function renderList(){ const wrap = document.getElementById('results'); const empty = document.getElementById('empty'); if (!wrap) return; let list = state.menu.filter(matchesQ); list = (state.mode==='safe') ? list.filter(isSafe) : list.filter(containsSel); wrap.innerHTML = list.map(d => `<article class="card"><h4>${d.dish}</h4><div>${d.codes.map(codeBadge).join(' ') || '<span class="badge">No codes</span>'}</div>${d.notes ? `<div class="note">${d.notes}</div>` : ''}</article>`).join(''); empty.style.display = list.length ? 'none' : 'block'; }
function renderChips(){ const box = document.getElementById('allergenList'); if (!box) return; box.innerHTML = state.allergens.map(pill).join(''); box.querySelectorAll('input[type=checkbox]').forEach(chk => { chk.addEventListener('change', e => { const c = e.target.value; if (e.target.checked) state.selected.add(c); else state.selected.delete(c); renderFilters(); renderList(); }); }); }
function wire(){ const s = document.getElementById('search'); if (s) s.addEventListener('input', e => { state.q = e.target.value; renderList(); }); const clr = document.getElementById('clearBtn'); if (clr) clr.addEventListener('click', () => { state.selected.clear(); document.querySelectorAll('#allergenList input[type=checkbox]').forEach(c=>c.checked=false); if (s) s.value=''; state.q=''; renderFilters(); renderList(); }); document.querySelectorAll('input[name="mode"]').forEach(r => r.addEventListener('change', e => { state.mode = e.target.value; renderList(); })); }
async function load(){ const [aRes, mRes] = await Promise.all([fetch('allergens.json'), fetch('menu.json')]); state.allergens = await aRes.json(); state.menu = await mRes.json(); renderChips(); renderList(); }
wire(); load();
