const state = { allergens: [], menu: [], selected: new Set(), mode: 'safe', q: '' };
function codePill(code){ return `<span class="pill">${code}</span>`; }
function renderFilters(){ const el=document.getElementById('activeFilters'); el && (el.innerHTML = state.selected.size ? ('Selected: ' + Array.from(state.selected).map(codePill).join(' ')) : ''); }
function matchesQuery(d){ if(!state.q) return true; const q=state.q.toLowerCase(); return d.dish.toLowerCase().includes(q) || (d.notes||'').toLowerCase().includes(q); }
function isSafe(d){ for(const c of state.selected){ if(d.codes.includes(c)) return false; } return true; }
function containsSelected(d){ if(!state.selected.size) return false; for(const c of state.selected){ if(d.codes.includes(c)) return true; } return false; }
function renderResults(){ const res=document.getElementById('results'); const empty=document.getElementById('empty'); let list=state.menu.filter(matchesQuery); list=(state.mode==='safe')?list.filter(isSafe):list.filter(containsSelected); if(res){ res.innerHTML=list.map(d=>`<div class="result"><h4>${d.dish}</h4><div><span class="codes">Codes: ${d.codes.join(', ') || '—'}</span></div>${d.notes?`<div class="note" style="margin-top:6px;">${d.notes}</div>`:''}</div>`).join(''); } if(empty){ empty.style.display=list.length?'none':'block'; } }
function renderAllergenList(){ const box=document.getElementById('allergenList'); if(!box) return; box.innerHTML=state.allergens.map(a=>`<label class="chk"><input type="checkbox" value="${a.code}"><span>${a.code}</span> · <span class="note">${a.name}</span></label>`).join(''); box.querySelectorAll('input[type=checkbox]').forEach(chk=>{ chk.addEventListener('change',e=>{ const c=e.target.value; if(e.target.checked) state.selected.add(c); else state.selected.delete(c); renderFilters(); renderResults(); }); }); }
function wire(){ const s=document.getElementById('search'); if(s){ s.addEventListener('input',e=>{ state.q=e.target.value; renderResults(); }); } const clr=document.getElementById('clearBtn'); if(clr){ clr.addEventListener('click',()=>{ state.selected.clear(); document.querySelectorAll('#allergenList input[type=checkbox]').forEach(c=>c.checked=false); if(s) s.value=''; state.q=''; renderFilters(); renderResults(); }); } document.querySelectorAll('input[name="mode"]').forEach(r=>{ r.addEventListener('change',e=>{ state.mode=e.target.value; renderResults(); }); }); }
async function load(){ const [a,m]=await Promise.all([fetch('allergens.json'), fetch('menu.json')]); state.allergens=await a.json(); state.menu=await m.json(); renderAllergenList(); renderResults(); }
wire(); load();
